# Data Preprocessing

### Importing nessessary libraries

In [68]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from statistics import *
from tabulate import tabulate

### loading the data into pandas dataframe

## Step 1) Variable Identification

In [73]:
df = pd.read_csv('../data/Week1_challenge_data_source(CSV).csv', na_values=['?', None])
df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

## Step 2) Data Understanding

In [21]:
df.size

8250055

In [22]:
df.shape

(150001, 55)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [27]:
df.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.490100e+05,150000.000000,150000.000000,1.500000e+05,1.494310e+05,1.489350e+05,1.494290e+05,122172.000000,122189.000000,150000.000000,...,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500000e+05,1.500000e+05
mean,1.013887e+19,499.188200,498.800880,1.046086e+05,2.082016e+14,4.188282e+10,4.847455e+13,109.795706,17.662883,13300.045927,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.893173e+18,288.611834,288.097653,8.103762e+04,2.148809e+10,2.447443e+12,2.241637e+13,619.782739,84.793524,23971.878541,...,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127639e+07,2.441429e+08
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,...,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,250.000000,251.000000,5.744050e+04,2.082014e+14,3.365130e+10,3.546071e+13,32.000000,2.000000,43.000000,...,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322201e+07,2.431068e+08
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572201e+13,45.000000,5.000000,63.000000,...,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114331e+07,4.558411e+08
75%,1.304243e+19,749.000000,750.000000,1.324302e+05,2.082018e+14,3.368349e+10,8.611970e+13,70.000000,15.000000,19710.750000,...,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657055e+08
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.140743e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,...,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

In [33]:
df['Bearer Id'].mode()

0    1.304243e+19
dtype: float64

In [40]:
# Count of unique values of a column

print('\nNumber of unique values => ' + str(len(df['Bearer Id'].unique())))
print('\nNumber of unique values => ' + str(len(df['IMSI'].unique())))
print('\nNumber of unique values => ' + str(len(df['MSISDN/Number'].unique())))

Number of unique values => 134709

Number of unique values => 107266

Number of unique values => 106857

In [41]:
# List of all unique values of a column

print('\nUnique values are => \n\n' + str(pd.Series(df['MSISDN/Number'].unique()).sort_values(ascending=True)))

Unique values are =>

34600    3.360100e+10
94576    3.360100e+10
99079    3.360100e+10
73278    3.360101e+10
13613    3.360101e+10
             ...
47259    3.379000e+10
76514    3.197021e+12
93633    3.370000e+14
93065    8.823971e+14
226               NaN
Length: 106857, dtype: float64

In [42]:
# Frequency Distribution of unique values of a column

print('\nFrequency distribution of unique values => \n\n'+ str(df['MSISDN/Number'].value_counts(dropna=False).sort_values(ascending = False)))

Frequency distribution of unique values =>

NaN             1066
3.362632e+10      18
3.361489e+10      17
3.362578e+10      17
3.365973e+10      16
                ...
3.366364e+10       1
3.366742e+10       1
3.366556e+10       1
3.376148e+10       1
3.366483e+10       1
Name: MSISDN/Number, Length: 106857, dtype: int64

In [43]:
# Distinct value counts/frequencies of each column to determine if there are any columns with only a single value/all different values

pd.DataFrame(df.apply(lambda x: len(x.value_counts(dropna=False)), axis=0), columns=['Unique Value Count']).sort_values(by='Unique Value Count', ascending=True)

                                          Unique Value Count
UL TP > 300 Kbps (%)                                      64
50 Kbps < UL TP < 300 Kbps (%)                            69
250 Kbps < DL TP < 1 Mbps (%)                             74
50 Kbps < DL TP < 250 Kbps (%)                            85
10 Kbps < UL TP < 50 Kbps (%)                             86
DL TP > 1 Mbps (%)                                        86
UL TP < 10 Kbps (%)                                       99
DL TP < 50 Kbps (%)                                      101
Handset Manufacturer                                     171
Avg RTT UL (ms)                                          723
Start ms                                                1001
End ms                                                  1001
Nb of sec with 37500B < Vol UL                          1105
Handset Type                                            1397
Nb of sec with 6250B < Vol UL < 37500B                  1711
Avg RTT DL (ms)                                         2131
Nb of sec with 1250B < Vol UL < 6250B                   3399
Nb of sec with 31250B < Vol DL < 125000B                5756
Nb of sec with 6250B < Vol DL < 31250B                  6173
End                                                     6404
Nb of sec with 125000B < Vol DL                         6459
Start                                                   9998
Avg Bearer TP UL (kbps)                                14529
Nb of sec with Vol DL < 6250B                          22271
Nb of sec with Vol UL < 1250B                          22977
TCP UL Retrans. Vol (Bytes)                            35121
Avg Bearer TP DL (kbps)                                41754
Last Location Name                                     45548
TCP DL Retrans. Vol (Bytes)                            54400
Social Media UL (Bytes)                                59078
HTTP UL (Bytes)                                        59943
HTTP DL (Bytes)                                        63528
Dur. (ms)                                              89526
Activity Duration DL (ms)                             102561
Activity Duration UL (ms)                             106293
MSISDN/Number                                         106857
IMSI                                                  107266
IMEI                                                  107271
Dur. (ms).1                                           122872
Bearer Id                                             134709
Email UL (Bytes)                                      138699
Social Media DL (Bytes)                               146856
Email DL (Bytes)                                      146916
Google UL (Bytes)                                     147267
Google DL (Bytes)                                     149024
Other UL (Bytes)                                      149284
Gaming UL (Bytes)                                     149316
Youtube UL (Bytes)                                    149477
Netflix UL (Bytes)                                    149490
Netflix DL (Bytes)                                    149518
Youtube DL (Bytes)                                    149547
Total UL (Bytes)                                      149729
Gaming DL (Bytes)                                     149983
Other DL (Bytes)                                      149986
Total DL (Bytes)                                      149988

In [72]:
def find_min_max_in(df, col):
    """
    The function takes in a column and returns the top 5
    and bottom 5 in dataframe in that column.
    args:
        col: string - column name
    return:
        info_df: dataframe - final 5 dataframe
    """
    top = df[col].idxmax()
    top_df = pd.DataFrame(df.loc[top])
    bottom = df[col].idxmin()
    bottom_df = pd.DataFrame(df.loc[bottom])
    info_df = pd.concat([top_df, bottom_df], axis=1)
    return info_df

find_min_max_in(df, 'Total DL (Bytes)')

# This usually is helpful to understand various attributes of max and min values of a particular column. 
# This can also help to decide which column to keep for further analysis.

,61396,1932
Bearer Id,7.34988e+18,1.30424e+19
Start,4/26/2019 4:36,4/24/2019 2:05
Start ms,42,375
End,4/27/2019 3:30,4/25/2019 2:05
End ms,336,257
Dur. (ms),82424,86399
IMSI,2.08202e+14,2.08201e+14
MSISDN/Number,3.37813e+10,3.3661e+10
IMEI,3.57654e+13,8.65408e+13
Last Location Name,D61328C,9.16456685919642E+015
Avg RTT DL (ms),NaN,432
Avg RTT UL (ms),NaN,34
Avg Bearer TP DL (kbps),50,16261
Avg Bearer TP UL (kbps),58,7308
TCP DL Retrans. Vol (Bytes),NaN,1.27715e+07
TCP UL Retrans. Vol (Bytes),NaN,137294
DL TP < 50 Kbps (%),100,82
50 Kbps < DL TP < 250 Kbps (%),0,10
250 Kbps < DL TP < 1 Mbps (%),0,5
DL TP > 1 Mbps (%),0,0
UL TP < 10 Kbps (%),100,97
10 Kbps < UL TP < 50 Kbps (%),0,1
50 Kbps < UL TP < 300 Kbps (%),0,0
UL TP > 300 Kbps (%),0,0
HTTP DL (Bytes),NaN,7.42488e+06
HTTP UL (Bytes),NaN,598091
Activity Duration DL (ms),12465,4.06305e+06
Activity Duration UL (ms),21336,3.0265e+06
Dur. (ms).1,8.24243e+07,8.63999e+07
Handset Manufacturer,Samsung,Huawei
Handset Type,Samsung Galaxy A3 (Sm-A320),Huawei E5180
Nb of sec with 125000B < Vol DL,NaN,111
Nb of sec with 1250B < Vol UL < 6250B,NaN,120
Nb of sec with 31250B < Vol DL < 125000B,NaN,796
Nb of sec with 37500B < Vol UL,NaN,71
Nb of sec with 6250B < Vol DL < 31250B,NaN,1396
Nb of sec with 6250B < Vol UL < 37500B,NaN,19
Nb of sec with Vol DL < 6250B,74,11129
Nb of sec with Vol UL < 1250B,115,8572
Social Media DL (Bytes),2.13863e+06,108668
Social Media UL (Bytes),23067,19621
Google DL (Bytes),9.82317e+06,1.53755e+06
Google UL (Bytes),693275,1.29283e+06
Email DL (Bytes),2.89899e+06,65164
Email UL (Bytes),887607,127715
Youtube DL (Bytes),2.22862e+07,541851
Youtube UL (Bytes),1.18201e+07,9.84373e+06
Netflix DL (Bytes),2.25153e+07,2.6931e+06
Netflix UL (Bytes),1.00763e+07,3.0066e+06
Gaming DL (Bytes),8.43307e+08,2.16771e+06
Gaming UL (Bytes),351060,583513
Other DL (Bytes),7.04395e+08,5.26443e+08
Other UL (Bytes),1.02301e+07,9.1053e+06
Total UL (Bytes),3.40815e+07,2.39793e+07
Total DL (Bytes),9.0297e+08,7.11404e+06

## Step 3) Data Cleaning/Manipulation

#### Fixing Columns
##### Dropping Columns with Single Value

In [59]:

db_single=df.copy()

single_value_columns = pd.DataFrame(db_single.apply(lambda x: len(x.value_counts()), axis=0), columns=['SingleValueColumn'])

drop_single_value_columns = list(single_value_columns.loc[single_value_columns['SingleValueColumn']==1].index)

print('Columns which have just a single value => \n\n' + str(drop_single_value_columns))

df.drop(drop_single_value_columns, axis=1, inplace=True)

print('\n\nRemaining Columns => ' + str(len(df.columns)))

Columns which have just a single value =>

[]


Remaining Columns => 55

#### Dropping Columns with All Different Values

In [60]:
db_diff=df.copy()

alldiff_value_columns = pd.DataFrame(db_diff.apply(lambda x: len(x.value_counts()), axis=0), columns=['AllDiffValueColumn'])

drop_alldiff_value_columns = list(alldiff_value_columns.loc[alldiff_value_columns['AllDiffValueColumn']==len(df.index)].index)

print('Columns which have all values different => \n\n' + str(drop_alldiff_value_columns))

df.drop(drop_alldiff_value_columns, axis=1, inplace=True)

print('\n\nRemaining Columns => ' + str(len(df.columns)))

Columns which have all values different =>

[]


Remaining Columns => 55

#### Duplicate Data

In [62]:
# Count of duplicates
df.duplicated().value_counts()
# Drop duplicates
df.drop_duplicates(keep='first', inplace=True)
df.drop_duplicates(subset=['MSISDN/Number'], keep='first', inplace=True)

#### Missing Values

In [81]:
# Any missing values
df.isnull().values.any()

# Total number of missing values
df.isnull().sum().sum()

############### Column Wise ###############
df.isna().sum() # Count of nulls in each column

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64